src/parser.rs
src/shell.rs
src/test.rs

These pipelines map stdout and stderr to stdin of the next command.
Closes #12.

feat: support `|&` pipelines

---

src/commands/mod.rs
src/commands/pwd.rs
src/shell.rs
src/shell_types.rs
src/test.rs

I missed doing this on this command. We should disallow flags when using pwd until we implement them.

fix: disallow args/flags on `pwd` for now

---

src/combinators.rs
src/parser.rs
src/shell.rs
src/test.rs

I was investigating adding glob support and was thinking about file paths with spaces in the name. That's when I realized this functionality was broken. See the tests for examples of what's now fixed. It's not perfect still... just an incremental improvement.

fix: allow escaping spaces in words

---

src/combinators.rs
src/parser.rs

Using `ch` instead of `character` because its short and used a lot so easy to remember what it means.
Reason is because the `char` identifier shows up as the `char` keyword after syntax highlighting. https://github.com/denoland/deno_task_shell/pull/21/files#r830417175 -- `char` was initially used to align with nom.

refactor: fn `char` to `ch`

---

src/shell.rs
src/test.rs
src/test_builder.rs

1. Fix case sensistive comparison which should have been case insensitive
2. Fix to handle `PATHEXT` with a trailing semi-colon
Closes #27

fix: handle `PATHEXT` with trailing semi-colon

---

src/shell.rs

For https://github.com/denoland/deno/issues/14427

feat: always resolve the current executable path for the `deno` command name

---

Cargo.lock
Cargo.toml
src/shell/commands/cat.rs
src/shell/commands/cp_mv.rs
src/shell/commands/rm.rs
src/shell/commands/sleep.rs
src/shell/mod.rs
src/shell/test.rs
src/shell/types.rs

This changes async commands so that on non-zero exit code they will fail the entire task. For example:
```jsonc
// task that asynchronously starts a server and starts a watcher for the frontend 
"dev": "deno task server & deno task frontend:watch"
```
Previously when running `deno task dev`, if `deno task server` failed, the entire command would not fail, which kept in line with `sh`, but it's not very practical. This change causes `deno task dev` to fail.
To opt out, developers can add an `|| exit 0`:
```jsonc
"dev": "deno task server || exit 0 & deno task frontend:watch"
```
Closes #50

feat(breaking): fail task on async command failure

---

Cargo.lock
Cargo.toml
src/parser.rs

I accidentally did a breaking change in a patch (which I've yanked), so let's revert the signature, but I will also upgrade monch again.

fix: revert signature to not be breaking

---

src/shell/commands/cat.rs
src/shell/commands/cd.rs
src/shell/commands/cp_mv.rs
src/shell/commands/echo.rs
src/shell/commands/exit.rs
src/shell/commands/export.rs
src/shell/commands/mkdir.rs
src/shell/commands/mod.rs
src/shell/commands/pwd.rs
src/shell/commands/rm.rs
src/shell/commands/sleep.rs
src/shell/commands/xargs.rs
src/shell/mod.rs
src/shell/types.rs

This creates a `ShellCommand` trait. In a PR after this I will expose this in the API. It should allow us to inject npm binary commands.

refactor: create `ShellCommand` trait

---

src/shell/commands/cat.rs
src/shell/commands/cd.rs
src/shell/commands/cp_mv.rs
src/shell/commands/executable.rs
src/shell/commands/mkdir.rs
src/shell/commands/mod.rs
src/shell/commands/pwd.rs
src/shell/commands/rm.rs
src/shell/commands/sleep.rs
src/shell/commands/xargs.rs
src/shell/mod.rs
src/shell/test_builder.rs
src/shell/types.rs

This refactors out the code that resolves and executes a command in a separate process, makes it implement a `ShellCommand`, then exposes that.

feat: add and expose ExecutableCommand

---

src/shell/test.rs
src/shell/types.rs

This commit allows empty values for env vars in order to make the behavior consistent with the normal command execution.
Suppose we set an env var called FOO with `export FOO=` (note this is an empty), and we have a simple script that prints this env var:
```ts
console.log(`Foo: ${Deno.env.get("FOO")}`);
```
Running this script via `deno run` gets us `Foo: `.
While via `deno task` (with "foo": "deno run --allow-env foo.ts" in deno.json) it gets us `Foo: undefined`.
This might be a significant difference if it matters whether the env var is set or not. So this PR fixes this behavior by always setting given env vars even if they are empty.
I'm not really sure if there's a place where I can write a test case. Please let me know if there should be a test case.

fix: allow empty values for env vars by always inserting value

---

src/shell/commands/mod.rs
src/shell/commands/unset.rs
src/shell/test.rs
src/shell/types.rs

This commit implements a new built-in command `unset` that simulates [POSIX's unset](https://man7.org/linux/man-pages/man1/unset.1p.html). It enables to completely unset shell variables or environment variables.

feat: add `unset` command

---

src/lib.rs
src/shell/mod.rs
src/shell/test_builder.rs
src/shell/types.rs

As requested in #86 we want to use the `deno_task_shell` in the same way as `deno` does.
We would like to run tests as the `test_builder` is doing for this project.
This PR makes `execute_with_pipes` a public function and the necessary functions to run the tests with that as well. 
I also tried to add some documentation, please check if I interpreted the code correctly. 
To see what we did with it check out this PR: https://github.com/prefix-dev/pixi/pull/173
Thanks for making this a library! 
Closes #86

feat: expose execute_with_pipes and the needed functions

---

src/parser.rs
src/shell/mod.rs
src/shell/test.rs

For https://github.com/denoland/deno/issues/19942

fix: ensure single quoted strings are maintained mid-word

---

src/shell/commands/head.rs
src/shell/commands/mod.rs
src/shell/test.rs
src/shell/types.rs

This patch partially addresses issue #92.  It implements the very basic `head` command, with the following limitations:
- It can accept at most one file.
- The only options it supports are `-n`/`--lines`.
- The `-n`/`--lines` option cannot accept negative numbers.

feat: add basic `head` command

---

src/shell/commands/executable.rs
src/shell/test.rs

We got [the request](https://github.com/prefix-dev/pixi/issues/485) to act on command not found. I though this might be a nice addition to the task shell itself. 
What do you think?

fix: exit with code 127 on command not found

---

src/parser.rs
src/shell/mod.rs
src/shell/test.rs
src/shell/types.rs

Supports input redirects where the specified file on the right hand side is redirected to the stdin of the pipeline on the left:
```
gzip < file.txt
```
(I want this for Dax because I'm investigating doing something similar to Bun's shell in Dax where you can provide objects to the shell. I got it working, but not sure how I feel about it though because other APIs seem better and more clear)

feat: support file input redirects

---

rust-toolchain.toml
src/parser.rs
src/shell/mod.rs
src/shell/test.rs

For https://github.com/denoland/deno/issues/22989

feat: implement exit status var

---

src/parser.rs
src/shell/mod.rs
src/shell/test.rs
src/shell/types.rs

~~Waiting on https://github.com/denoland/deno_task_shell/pull/106~~
This implements fd redirects in the parser (because I want it for Dax). We can do the shell implementation later.

feat: support parsing fd redirects

---

src/shell/commands/exit.rs
src/shell/test.rs

fix: exit error code on arg parse failure

---

Cargo.lock
Cargo.toml
src/shell/commands/executable.rs
src/shell/commands/mod.rs
src/shell/mod.rs
src/shell/test.rs

feat: initial cross-platform shebang support

---

src/shell/command.rs
src/shell/commands/mod.rs
src/shell/mod.rs
src/shell/test.rs

Will be for getting the path to the `npx` executable.

feat: `ShellCommandContext` - ability to resolve path to command

---

src/shell/execute.rs
src/shell/test.rs

fix: do not propogate env changes outside subshells

---

src/shell/commands/mod.rs
src/shell/execute.rs
src/shell/test.rs
src/shell/types.rs

For the future. I just realized this when debugging something in the CLI.
This moves the method to where the other functionality is and this is more versatile.

fix(BREAKING): move `.resolve_command_path` to `ShellState`

---

src/shell/command.rs
src/shell/mod.rs
src/shell/types.rs
src/shell/which.rs

* `deno_task_shell::which::resolve_command_path(...) -> Result<PathBuf, ...>`

feat: expose lightweight API for resolving a command path

---

.github/workflows/ci.yml
.github/workflows/release.yml
src/shell/test.rs
src/shell/which.rs

For https://github.com/denoland/deno/issues/26005

fix: use current deno executable even when not named deno

---

Cargo.lock
Cargo.toml
src/shell/commands/cat.rs
src/shell/commands/cp_mv.rs
src/shell/commands/executable.rs
src/shell/commands/head.rs
src/shell/commands/mkdir.rs
src/shell/commands/mod.rs
src/shell/commands/rm.rs
src/shell/commands/sleep.rs
src/shell/execute.rs
src/shell/mod.rs
src/shell/test.rs
src/shell/test_builder.rs
src/shell/types.rs

This is a more advanced and appropriate form of a cancellation token.
For https://github.com/denoland/deno_task_shell/issues/33

feat: introduce `KillSignal` for sending signals to tasks

---

Cargo.lock
Cargo.toml

The nix bump in particular is required to unbreak builds for s390x-unknown-linux-musl in dependent applications / libraries like pixi.

fix: update `thiserror` and `nix`

---

src/parser.rs
tests/integration_test.rs

Backticks are just command substitution, so no execution changes are necessary.
For https://github.com/denoland/deno/issues/28807

feat: support backticks

---

.github/workflows/ci.yml
Cargo.toml

This isn't necessary when only using deno_task_shell for serialization in Wasm.

fix: move sys_traits to shell feature to fix Wasm build

---

Cargo.lock
Cargo.toml
LICENSE.md
src/lib.rs
src/parser.rs
src/shell/command.rs
src/shell/commands/args.rs
src/shell/commands/cat.rs
src/shell/commands/cd.rs
src/shell/commands/cp_mv.rs
src/shell/commands/echo.rs
src/shell/commands/executable.rs
src/shell/commands/exit.rs
src/shell/commands/export.rs
src/shell/commands/head.rs
src/shell/commands/mkdir.rs
src/shell/commands/mod.rs
src/shell/commands/pwd.rs
src/shell/commands/rm.rs
src/shell/commands/sleep.rs
src/shell/commands/unset.rs
src/shell/commands/xargs.rs
src/shell/execute.rs
src/shell/fs_util.rs
src/shell/mod.rs
src/shell/types.rs
src/shell/which.rs
tests/integration_test.rs
tests/test_builder.rs

* https://github.com/harryfei/which-rs/pull/109

fix(BREAKING): use `which` crate and drop resolving Deno to current exe
